# Plugin parameter set for the "ec_swift" robot. See athena.yaml for the type convention
# (double-valued parameters must be written with a decimal point).
drive_plugin:
  slow_factor: 0.5
  fast_factor: 2.0
  max_angular_speed: 2.0
  max_linear_speed: 1.0
