description: Drive the robot and control the flippers

axes:
  left_stick_x:
    plugin: hector_gamepad_manager_plugins::DrivePlugin
    function: steer
    description: Steer

  left_stick_y:
    plugin: hector_gamepad_manager_plugins::DrivePlugin
    function: drive
    description: Drive forward/backward

  left_trigger:
    plugin: hector_gamepad_manager_plugins::FlipperPlugin
    function: flipper_back_down
    description: Lower back flippers

  right_stick_x:
    plugin: hector_gamepad_manager_plugins::VirtualCameraPlugin
    function: camera_pan
    description: Pan camera

  right_stick_y:
    plugin: hector_gamepad_manager_plugins::VirtualCameraPlugin
    function: camera_tilt
    description: Tilt camera

  right_trigger:
    plugin: hector_gamepad_manager_plugins::FlipperPlugin
    function: flipper_front_down
    description: Lower front flippers

buttons:
  a:
    plugin: hector_gamepad_manager_plugins::DrivePlugin
    function: slow
    description: Drive slowly (hold)

  b:
    plugin: hector_gamepad_manager_plugins::FlipperPlugin
    on_press:
      function: individual_front_flipper_control_mode
      description: Control front flippers individually
    on_double_press:
      function: sync_front_flippers
      description: Sync front flippers

  x:
    plugin: hector_gamepad_manager_plugins::FlipperPlugin
    on_press:
      function: individual_back_flipper_control_mode
      description: Control back flippers individually
    on_double_press:
      function: sync_back_flippers
      description: Sync back flippers

  y:
    plugin: hector_gamepad_manager_plugins::DrivePlugin
    function: fast
    description: Drive fast (hold)

  left_bumper:
    plugin: hector_gamepad_manager_plugins::FlipperPlugin
    on_press:
      function: flipper_back_up
      description: Raise back flippers
    on_double_press:
      function: flipper_back_upright
      description: Back flippers to upright position

  right_bumper:
    plugin: hector_gamepad_manager_plugins::FlipperPlugin
    on_press:
      function: flipper_front_up
      description: Raise front flippers
    on_double_press:
      function: flipper_front_upright
      description: Front flippers to upright position

  back:
    plugin: ''
    function: ''

  start:
    plugin: ''
    function: ''

  guide: # Button Guide (Manufacturer Button)
    plugin: hector_gamepad_manager_plugins::BlackboardPlugin
    function: toggle
    description: Toggle inverted steering
    args:
      name: invert_steering
      ocs_topic: joy_teleop_direction

  left_stick_click:
    plugin: hector_gamepad_manager_plugins::BlackboardPlugin
    function: toggle
    description: Toggle software emergency stop
    args:
      name: software_e_stop
      initial: 'false'
      topic: gamepad_e_stop


  right_stick_click:
    plugin: hector_gamepad_manager_plugins::VirtualCameraPlugin
    function: reset_camera
    description: Reset camera view

  share: # Button Share (only on newer Xbox controllers)
    plugin: hector_gamepad_manager_plugins::BlackboardPlugin
    function: toggle
    description: Toggle inverted steering
    args:
      name: invert_steering
      ocs_topic: joy_teleop_direction

  dpad_left:
    plugin: hector_gamepad_manager_plugins::MoveitPlugin
    function: go_to_pose
    description: Flippers to tub pose
    args:
      group: flipper_group
      pose: tub

  dpad_right:
    plugin: hector_gamepad_manager_plugins::MoveitPlugin
    function: go_to_pose
    description: Flippers to compact pose
    args:
      group: flipper_group
      pose: compact

  dpad_up:
    plugin: hector_gamepad_manager_plugins::MoveitPlugin
    function: go_to_pose
    description: Flippers to up pose
    args:
      group: flipper_group
      pose: up

  dpad_down:
    plugin: hector_gamepad_manager_plugins::MoveitPlugin
    function: go_to_pose
    description: Flippers to flat pose
    args:
      group: flipper_group
      pose: flat

# -------------------- All the axes can also be used as buttons if specified here --------------------
axis_buttons:
  left_stick_left:
    plugin: ''
    function: ''

  left_stick_right:
    plugin: ''
    function: ''

  left_stick_up:
    plugin: ''
    function: ''

  left_stick_down:
    plugin: ''
    function: ''

  left_trigger:
    plugin: ''
    function: ''

  right_stick_left:
    plugin: ''
    function: ''

  right_stick_right:
    plugin: ''
    function: ''

  right_stick_up:
    plugin: ''
    function: ''

  right_stick_down:
    plugin: ''
    function: ''

  right_trigger:
    plugin: ''
    function: ''
