axes:
  0: # Left joystick left/right
    plugin: "hector_gamepad_manager_plugins::DrivePlugin"
    function: "steer"

  1: # Left joystick up/down
    plugin: "hector_gamepad_manager_plugins::DrivePlugin"
    function: "drive"

  2: # LT
    plugin: "hector_gamepad_manager_plugins::FlipperPlugin"
    function: "flipper_back_down"

  3: # Right joystick left/right
    plugin: ""
    function: ""

  4: # Right joystick up/down
    plugin: ""
    function: ""

  5: # RT
    plugin: "hector_gamepad_manager_plugins::FlipperPlugin"
    function: "flipper_front_down"

  6: # Cross left/right
    plugin: ""
    function: ""

  7: # Cross up/down
    plugin: ""
    function: ""

buttons:
  0: # Button A
    plugin: "hector_gamepad_manager_plugins::DrivePlugin"
    function: "fast"

  1: # Button B
    plugin: ""
    function: ""

  2: # Button X
    plugin: "hector_gamepad_manager_plugins::DrivePlugin"
    function: "slow"

  3: # Button Y
    plugin: ""
    function: ""

  4: # Button LB
    plugin: "hector_gamepad_manager_plugins::FlipperPlugin"
    function: "flipper_back_up"

  5: # Button RB
    plugin: "hector_gamepad_manager_plugins::FlipperPlugin"
    function: "flipper_front_up"

  6: # Button Back
    plugin: ""
    function: ""

  7: # Button Start
    plugin: ""
    function: ""

  8: # Button Guide (Manufacturer Button)
    plugin: ""
    function: ""

  9: # Left joystick press
    plugin: ""
    function: ""

  10: # Right joystick press
    plugin: ""
    function: ""

  # -------------------- All the axes can also be used as buttons if specified here --------------------
  11: # Left joystick left
    plugin: ""
    function: ""

  12: # Left joystick right
    plugin: ""
    function: ""

  13: # Left joystick up
    plugin: ""
    function: ""

  14: # Left joystick down
    plugin: ""
    function: ""

  15: # LT
    plugin: ""
    function: ""

  16: # Right joystick left
    plugin: ""
    function: ""

  17: # Right joystick right
    plugin: ""
    function: ""

  18: # Right joystick up
    plugin: ""
    function: ""

  19: # Right joystick down
    plugin: ""
    function: ""

  20: # RT
    plugin: ""
    function: ""

  21: # Cross left
    plugin: "hector_gamepad_manager_plugins::MoveitPlugin"
    function: "flipper_group/wanne"

  22: # Cross right
    plugin: "hector_gamepad_manager_plugins::MoveitPlugin"
    function: "flipper_group/small"

  23: # Cross up
    plugin: "hector_gamepad_manager_plugins::MoveitPlugin"
    function: "flipper_group/up"

  24: # Cross down
    plugin: "hector_gamepad_manager_plugins::MoveitPlugin"
    function: "flipper_group/flat"
