description: Simple driving controls

axes:
  left_stick_x:
    plugin: hector_gamepad_manager_plugins::DrivePlugin
    function: steer
    description: Steer

  left_stick_y:
    plugin: hector_gamepad_manager_plugins::DrivePlugin
    function: drive
    description: Drive forward/backward

  left_trigger:
    plugin: ''
    function: ''

  right_stick_x:
    plugin: ''
    function: ''

  right_stick_y:
    plugin: ''
    function: ''

  right_trigger:
    plugin: ''
    function: ''

buttons:
  a:
    plugin: hector_gamepad_manager_plugins::DrivePlugin
    function: slow
    description: Drive slowly (hold)

  b:
    plugin: ''
    function: ''

  x:
    plugin: ''
    function: ''

  y:
    plugin: hector_gamepad_manager_plugins::DrivePlugin
    function: fast
    description: Drive fast (hold)

  left_bumper:
    plugin: ''
    function: ''

  right_bumper:
    plugin: ''
    function: ''

  back:
    plugin: ''
    function: ''

  start:
    plugin: ''
    function: ''

  guide: # Button Guide (Manufacturer Button)
    plugin: ''
    function: ''

  left_stick_click:
    plugin: hector_gamepad_manager_plugins::BatteryMonitorPlugin
    function: mute
    description: Mute battery warnings

  right_stick_click:
    plugin: ''
    function: ''

  share: # Button Share (only on newer Xbox controllers)
    plugin: ''
    function: ''

  dpad_left:
    plugin: ''
    function: ''

  dpad_right:
    plugin: ''
    function: ''

  dpad_up:
    plugin: ''
    function: ''

  dpad_down:
    plugin: ''
    function: ''

# -------------------- All the axes can also be used as buttons if specified here --------------------
axis_buttons:
  left_stick_left:
    plugin: ''
    function: ''

  left_stick_right:
    plugin: ''
    function: ''

  left_stick_up:
    plugin: ''
    function: ''

  left_stick_down:
    plugin: ''
    function: ''

  left_trigger:
    plugin: ''
    function: ''

  right_stick_left:
    plugin: ''
    function: ''

  right_stick_right:
    plugin: ''
    function: ''

  right_stick_up:
    plugin: ''
    function: ''

  right_stick_down:
    plugin: ''
    function: ''

  right_trigger:
    plugin: ''
    function: ''
