axes:
  0: # Left joystick left/right
    plugin: "hector_gamepad_manager_plugins::DrivePlugin"
    function: "steer"

  1: # Left joystick up/down
    plugin: "hector_gamepad_manager_plugins::DrivePlugin"
    function: "drive"

  2: # LT
    plugin: ""
    function: ""

  3: # Right joystick left/right
    plugin: ""
    function: ""

  4: # Right joystick up/down
    plugin: ""
    function: ""

  5: # RT
    plugin: ""
    function: ""

  6: # Cross right/left
    plugin: ""
    function: ""

  7: # Cross up/down
    plugin: ""
    function: ""

buttons:
  0: # Button A
    plugin: "hector_gamepad_manager_plugins::DrivePlugin"
    function: "fast"

  1: # Button B
    plugin: ""
    function: ""

  2: # Button X
    plugin: "hector_gamepad_manager_plugins::DrivePlugin"
    function: "slow"

  3: # Button Y
    plugin: ""
    function: ""

  4: # Button LB
    plugin: ""
    function: ""

  5: # Button RB
    plugin: ""
    function: ""

  6: # Button Back
    plugin: ""
    function: ""

  7: # Button Start
    plugin: ""
    function: ""

  8: # Button Logitech
    plugin: ""
    function: ""

  9: # Left joystick press
    plugin: ""
    function: ""

  10: # Right joystick press
    plugin: ""
    function: ""
