axes:
  0: # Left joystick left/right
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "move_left_right"

  1: # Left joystick up/down
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "move_up_down"

  2: # LT
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "move_backward"

  3: # Right joystick left/right
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "rotate_yaw"

  4: # Right joystick up/down
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "rotate_pitch"

  5: # RT
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "move_forward"

  6: # Cross right/left
    plugin: ""
    function: ""

  7: # Cross up/down
    plugin: ""
    function: ""

buttons:
  0: # Button A
    plugin: ""
    function: ""

  1: # Button B
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "hold_mode"

  2: # Button X
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "gripper_close"

  3: # Button Y
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "gripper_open"

  4: # Button LB
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "rotate_roll_counter_clockwise"

  5: # Button RB
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "rotate_roll_clockwise"

  6: # Button Back
    plugin: ""
    function: ""

  7: # Button Start
    plugin: ""
    function: ""

  8: # Button Logitech
    plugin: ""
    function: ""

  9: # Left joystick press
    plugin: ""
    function: ""

  10: # Right joystick press
    plugin: ""
    function: ""
