axes:
  0: # Left joystick left/right
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "move_left_right"

  1: # Left joystick up/down
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "move_up_down"

  2: # LT
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "move_backward"

  3: # Right joystick left/right
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "rotate_yaw"

  4: # Right joystick up/down
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "rotate_pitch"

  5: # RT
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "move_forward"

  6: # Cross right/left
    plugin: ""
    function: ""

  7: # Cross up/down
    plugin: ""
    function: ""

buttons:
  0: # Button A
    plugin: ""
    function: ""

  1: # Button B
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "hold_mode"

  2: # Button X
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "gripper_close"

  3: # Button Y
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "gripper_open"

  4: # Button LB
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "rotate_roll_counter_clockwise"

  5: # Button RB
    plugin: "hector_gamepad_manager_plugins::ManipulationPlugin"
    function: "rotate_roll_clockwise"

  6: # Button Back
    plugin: ""
    function: ""

  7: # Button Start
    plugin: ""
    function: ""

  8: # Button Logitech
    plugin: ""
    function: ""

  9: # Left joystick press
    plugin: ""
    function: ""

  10: # Right joystick press
    plugin: ""
    function: ""

  # -------------------- All the axes can also be used as buttons if specified here --------------------
  11: # Left joystick left
    plugin: ""
    function: ""

  12: # Left joystick right
    plugin: ""
    function: ""

  13: # Left joystick up
    plugin: ""
    function: ""

  14: # Left joystick down
    plugin: ""
    function: ""

  15: # LT
    plugin: ""
    function: ""

  16: # Right joystick left
    plugin: ""
    function: ""

  17: # Right joystick right
    plugin: ""
    function: ""

  18: # Right joystick up
    plugin: ""
    function: ""

  19: # Right joystick down
    plugin: ""
    function: ""

  20: # RT
    plugin: ""
    function: ""

  21: # Cross left
    plugin: "hector_gamepad_manager_plugins::MoveitPlugin"
    function: "arm_group/back"

  22: # Cross right
    plugin: "hector_gamepad_manager_plugins::MoveitPlugin"
    function: "arm_group/front"

  23: # Cross up
    plugin: ""
    function: ""

  24: # Cross down
    plugin: "hector_gamepad_manager_plugins::MoveitPlugin"
    function: "arm_group/folded"
