axes:
  0: # Left joystick left/right
    plugin: "hector_gamepad_manager_plugins::ViewControlPlugin"
    function: "translate_x"

  1: # Left joystick up/down
    plugin: "hector_gamepad_manager_plugins::ViewControlPlugin"
    function: "translate_y"

  2: # LT
    plugin: "hector_gamepad_manager_plugins::ViewControlPlugin"
    function: "zoom_in"

  3: # Right joystick left/right
    plugin: "hector_gamepad_manager_plugins::ViewControlPlugin"
    function: "orbit_yaw"

  4: # Right joystick up/down
    plugin: "hector_gamepad_manager_plugins::ViewControlPlugin"
    function: "orbit_theta"

  5: # RT
    plugin: "hector_gamepad_manager_plugins::ViewControlPlugin"
    function: "zoom_out"

  6: # Cross left/right
    plugin: ""
    function: ""

  7: # Cross up/down
    plugin: ""
    function: ""

buttons:
  0: # Button A
    plugin: ""
    function: ""

  1: # Button B
    plugin: ""
    function: ""

  2: # Button X
    plugin: ""
    function: ""

  3: # Button Y
    plugin: ""
    function: ""

  4: # Button LB
    plugin: "hector_gamepad_manager_plugins::ViewControlPlugin"
    function: "move_up"

  5: # Button RB
    plugin: "hector_gamepad_manager_plugins::ViewControlPlugin"
    function: "move_down"

  6: # Button Back
    plugin: ""
    function: ""

  7: # Button Start
    plugin: ""
    function: ""

  8: # Button Guide (Manufacturer Button)
    plugin: ""
    function: ""

  9: # Left joystick press
    plugin: ""
    function: ""

  10: # Right joystick press
    plugin: ""
    function: ""

  # -------------------- All the axes can also be used as buttons if specified here --------------------
  11: # Left joystick left
    plugin: ""
    function: ""

  12: # Left joystick right
    plugin: ""
    function: ""

  13: # Left joystick up
    plugin: ""
    function: ""

  14: # Left joystick down
    plugin: ""
    function: ""

  15: # LT
    plugin: ""
    function: ""

  16: # Right joystick left
    plugin: ""
    function: ""

  17: # Right joystick right
    plugin: ""
    function: ""

  18: # Right joystick up
    plugin: ""
    function: ""

  19: # Right joystick down
    plugin: ""
    function: ""

  20: # RT
    plugin: ""
    function: ""

  21: # Cross left
    plugin: ""
    function: ""

  22: # Cross right
    plugin: ""
    function: ""

  23: # Cross up
    plugin: ""
    function: ""

  24: # Cross down
    plugin: ""
    function: ""
